# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a16120e44fc7184a61029455366325eb610a8ef67a6ae88446f13bc522c7d21f9e9a4cbbb60cfebbf59a75931bf6a9a22279ac53f4edba72317d162dc3df82ac

test:
  secret_key_base: ecc3388be4df73a070eb9aaa878d9e0353989540089ba19a1c0120629f5b5274b3db68c43e9788659407a2550a2fe3b05b36368ecaab279da3a5cdc21a03cb7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
